LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := cocos2dcpp_shared

LOCAL_MODULE_FILENAME := libcocos2dcpp

LOCAL_SRC_FILES := hellocpp/main.cpp \
                   ../../androidClasses/AppDelegate.cpp \
              	   ../../androidClasses/AliveInterface.cpp \
              	   ../../androidClasses/AttackState.cpp \
              	   ../../androidClasses/BattleScene.cpp \
              	   ../../androidClasses/ReadyToBattleScene.cpp \
              	   ../../androidClasses/TestScene.cpp \
              	   ../../androidClasses/BeAttackState.cpp \
              	   ../../androidClasses/DefendState.cpp \
              	   ../../androidClasses/DeviceInterface.cpp \
              	   ../../androidClasses/GXAnimateFX.cpp \
              	   ../../androidClasses/GXFSMclass.cpp \
              	   ../../androidClasses/GXFSMstate.cpp \
              	   ../../androidClasses/GXInteger.cpp \
              	   ../../androidClasses/GXJsonUtil.cpp \
              	   ../../androidClasses/GXRadioMenu.cpp \
              	   ../../androidClasses/GXScrollTMXTileMap.cpp \
              	   ../../androidClasses/GXScrollButton.cpp \
              	   ../../androidClasses/GXScrollView.cpp \
              	   ../../androidClasses/GXUtil.cpp \
              	   ../../androidClasses/HitCheckManager.cpp \
              	   ../../androidClasses/IbeAttack.cpp \
              	   ../../androidClasses/IbePart.cpp \
              	   ../../androidClasses/LoadingScene.cpp \
              	   ../../androidClasses/Mathlib.cpp \
              	   ../../androidClasses/MoveToAttack.cpp \
              	   ../../androidClasses/MyBattleMap.cpp \
              	   ../../androidClasses/MyBuilding.cpp \
              	   ../../androidClasses/MyContinueTiledMenuItemSprite.cpp \
              	   ../../androidClasses/MyDeployButton.cpp \
              	   ../../androidClasses/MyEntity.cpp \
              	   ../../androidClasses/MyGameFactory.cpp \
              	   ../../androidClasses/MyGameInfo.cpp \
              	   ../../androidClasses/MyHttpConnection.cpp \
              	   ../../androidClasses/MyJsonUtil.cpp \
              	   ../../androidClasses/MyMap.cpp \
              	   ../../androidClasses/MyMenu.cpp \
              	   ../../androidClasses/MyState.cpp \
              	   ../../androidClasses/MyTiledMenuItemSprite.cpp \
              	   ../../androidClasses/MyUnit.cpp \
              	   ../../androidClasses/MyUnitState.cpp \
              	   ../../androidClasses/MyUtil.cpp \
              	   ../../androidClasses/MyXueTiao.cpp \
              	   ../../androidClasses/NewCreateMap.cpp \
              	   ../../androidClasses/NewMap.cpp \
              	   ../../androidClasses/NewMenuDevice.cpp \
              	   ../../androidClasses/NewMenuSpriteItem.cpp \
              	   ../../androidClasses/NormalState.cpp \
              	   ../../androidClasses/PartInterface.cpp \
              	   ../../androidClasses/PartService.cpp \
              	   ../../androidClasses/PulsarNative_and.cpp \
              	   ../../androidClasses/RectPart.cpp \
              	   ../../androidClasses/StartScene.cpp \
              	   ../../androidClasses/MyPriorityMenu.cpp \
              	   ../../androidClasses/AoeDefendState.cpp \
              	   ../../androidClasses/CoordinateTrans.cpp \
              	   ../../androidClasses/GXBaseScene.cpp \
              	   ../../androidClasses/MyMenuItem.cpp \
              	   ../../androidClasses/ReadyToBuild.cpp \
              	   ../../androidClasses/MyBuildingCard.cpp \
              	   ../../androidClasses/CollectState.cpp \
              	   ../../androidClasses/GXFadeIn.cpp \
              	   ../../androidClasses/GXFadeOut.cpp \
              	   ../../androidClasses/GXScaleTo.cpp \
              	   ../../androidClasses/GXReverseSheild.cpp \
              	   ../../androidClasses/GXRepeatForever.cpp \
              	   ../../androidClasses/TransitonScene.cpp \
              	   ../../androidClasses/MyLevelBar.cpp \
              	   ../../androidClasses/MyProgressBar.cpp \
              	   ../../androidClasses/UnfinishedState.cpp \
              	   ../../androidClasses/MyAtlasNumber.cpp \
              	   ../../androidClasses/GXProgressBar.cpp \
              	   ../../androidClasses/GXRemoveFromParentsAction.cpp \
              	   ../../androidClasses/ResourceBeAttackState.cpp \
              	   ../../androidClasses/RuinState.cpp \
              	   ../../androidClasses/CreatorRuinState.cpp \
              	   ../../androidClasses/GXShieldTouchMenuItem.cpp \
              	   ../../androidClasses/MyUnitCard.cpp \
              	   ../../androidClasses/ResourceOnlyBeRobberState.cpp \
              	   ../../androidClasses/GXListView.cpp \
              	   ../../androidClasses/GXMsg.cpp \
              	   ../../androidClasses/BattleRuinState.cpp \
              	   ../../androidClasses/MyBattleState.cpp \
              	   ../../androidClasses/MyBattleBuilding.cpp \
              	   ../../androidClasses/MyContinueTiledSprite.cpp \
              	   ../../androidClasses/MyTiledInfo.cpp \
              	   ../../androidClasses/MyContinueBuilding.cpp \
              	   ../../androidClasses/MyTiledMenuItem.cpp \
              	   ../../androidClasses/MyMessageManage.cpp \
              	   ../../androidClasses/Newbie1Trigger.cpp \
              	   ../../androidClasses/Newbie2Trigger.cpp \
              	   ../../androidClasses/Newbie3Trigger.cpp \
              	   ../../androidClasses/Newbie4Trigger.cpp \
              	   ../../androidClasses/NewbieReadyTrigger.cpp \
              	   ../../androidClasses/NewbieQuest1ToBattle.cpp \
              	   ../../androidClasses/QuestManager.cpp \
              	   ../../androidClasses/NoResourceToDeployMessage.cpp \
              	   ../../androidClasses/NewbieMovieScene.cpp \
              	   ../../androidClasses/NewbieStartScene.cpp \
              	   ../../androidClasses/NewbieBattleScene.cpp \
              	   ../../androidClasses/NewbieReadyScene.cpp \
              	   ../../androidClasses/Newbie1Message.cpp \
              	   ../../androidClasses/Newbie1to2Message.cpp \
              	   ../../androidClasses/NewbieClickMessage.cpp \
              	   ../../androidClasses/ToFightMessage.cpp \
              	   ../../androidClasses/GXFX.cpp \
              	   ../../androidClasses/GXAnimateWithFx.cpp \
              	   ../../androidClasses/GXAnimate.cpp \
              	   ../../androidClasses/GXAntiCrack.cpp \
              	   ../../androidClasses/ChthiefScene.cpp \
              	   ../../androidClasses/ThiefScene.cpp \
              	   ../../androidClasses/GXCommander.cpp \
              	   ../../androidClasses/GXString.cpp \
              	   ../../androidClasses/GXArray.cpp \
              	   ../../androidClasses/MyMemberBean.cpp \
              	   ../../androidClasses/GXDictionary.cpp \
              	   ../../androidClasses/RepairState.cpp \
              	   ../../androidClasses/AsyUnionBean.cpp \
              	   ../../androidClasses/GXMessage.cpp \
              	   ../../androidClasses/PushTrigger.cpp \
              	   ../../androidClasses/UnionJoinScroll.cpp \
              	   ../../androidClasses/unionTrigger.cpp \
              	   ../../androidClasses/ContinueState.cpp \
              	   ../../androidClasses/SplitState.cpp \
              	   ../../androidClasses/GXChatHandler.cpp \
              	   ../../androidClasses/GXFadeOutAndRemoveWhenStop.cpp \
              	   ../../androidClasses/MyShopCard.cpp \
              	   ../../androidClasses/GXResourceLoader.cpp \
              	   ../../androidClasses/BingYing.cpp \
              	   ../../androidClasses/kuangChang.cpp \
              	   ../../androidClasses/YouTian.cpp \
              	   ../../androidClasses/Wall.cpp \
              	   ../../androidClasses/ZhiHuiSuo.cpp \
              	   ../../androidClasses/LianLuoZhongXin.cpp \
              	   ../../androidClasses/DiaoBao.cpp \
              	   ../../androidClasses/DaPao.cpp \
              	   ../../androidClasses/CombineWall.cpp \
              	   ../../androidClasses/Ornament.cpp \
              	   ../../androidClasses/SuperKuangChang.cpp \
              	   ../../androidClasses/SuperYouTian.cpp \
              	   ../../androidClasses/UnitBean.cpp \
              	   ../../androidClasses/Garade.cpp \
              	   ../../androidClasses/M5Stuart.cpp \
              	   ../../androidClasses/Panzergrenadier.cpp \
              	   ../../androidClasses/WillysMB.cpp \
              	   ../../androidClasses/Infanterie.cpp \
              	   ../../androidClasses/M3HalfTrack.cpp \
              	   ../../androidClasses/M4Sherman.cpp \
              	   ../../androidClasses/Calliope.cpp \
              	   ../../androidClasses/HummingBird.cpp \
              	   ../../androidClasses/ServerScene.cpp \
              	   ../../androidClasses/ServerScene2.cpp \
              	   ../../androidClasses/StoreTrigger.cpp \
              	   ../../androidClasses/UpdateArmyMessage.cpp \
              	   ../../androidClasses/UpdateBuildingMessag.cpp \
              	   ../../androidClasses/FlyMoveToAttack.cpp \
              	   ../../androidClasses/GXShakeAction.cpp \
              	   ../../androidClasses/TransitionTrigger.cpp \
              	   ../../androidClasses/FlyAttackState.cpp \
              	   ../../androidClasses/LoginTrigger.cpp \
              	   ../../androidClasses/ServerSelectScroll.cpp \
              	   ../../androidClasses/ServerSelectScroll2.cpp \
              	   ../../androidClasses/GXLineSprite.cpp \
              	   ../../androidClasses/BuildingInfo.cpp \
              	   ../../androidClasses/GarbageCenter.cpp \
              	   ../../androidClasses/GarbageCollectionState.cpp \
              	   ../../androidClasses/GarbageCollectionNormalState.cpp \
              	   ../../androidClasses/Ghost.cpp \
              	   ../../androidClasses/ArmyQuest.cpp \
              	   ../../androidClasses/EveryDayTask1.cpp \
              	   ../../androidClasses/BuildingQuest.cpp \
              	   ../../androidClasses/PowerQuest.cpp \
              	   ../../androidClasses/BattleQuest.cpp \
              	   ../../androidClasses/DefendQuest.cpp \
              	   ../../androidClasses/LevelQuest.cpp \
              	   ../../androidClasses/DefendScene.cpp \
              	   ../../androidClasses/Volksgrenadier.cpp \
              	   ../../androidClasses/DefendOverMessage.cpp \
              	   ../../androidClasses/BattleOverMessage.cpp \
              	   ../../androidClasses/UpLevelMessage.cpp \
              	   ../../androidClasses/QuestUpdateMessage.cpp \
              	   ../../androidClasses/ResendOrder.cpp \
              	   ../../androidClasses/PanzerIV.cpp \
              	   ../../androidClasses/Tiger.cpp \
              	   ../../androidClasses/Cellar.cpp \
              	   ../../androidClasses/CellarProtectState.cpp \
              	   ../../androidClasses/AoeAttackState.cpp \
              	   ../../androidClasses/ReadyToBattleTrigger.cpp \
              	   ../../androidClasses/GXScissorNode.cpp \
              	   ../../androidClasses/GXScrollViewNoScissor.cpp \
              	   ../../androidClasses/GXScrollBar.cpp \
              	   ../../androidClasses/Tornado.cpp \
              	   ../../androidClasses/Thor.cpp \
              	   ../../androidClasses/DiaLayer.cpp \
              	   ../../androidClasses/TalkNode.cpp \
              	   ../../androidClasses/GXPlayAudioEffectCreator.cpp \
              	   ../../androidClasses/GXLabelTTFCreator.cpp \
              	   ../../androidClasses/GXSpriteCreator.cpp \
              	   ../../androidClasses/GXDelayTimeCreator.cpp \
              	   ../../androidClasses/GXSequenceCreator.cpp \
              	   ../../androidClasses/GXTintToCreator.cpp \
              	   ../../androidClasses/GXFadeToCreator.cpp \
              	   ../../androidClasses/MyBaseQuest.cpp \
              	   ../../androidClasses/TornadoMoveToAttack.cpp \
              	   ../../androidClasses/RobotMoveToAttack.cpp \
              	   ../../androidClasses/TornadoAttack.cpp \
              	   ../../androidClasses/MainMenuScroll2.cpp \
              	   ../../androidClasses/DialogCompleteMessage.cpp \
              	   ../../androidClasses/DefendInCreateState.cpp \
              	   ../../androidClasses/GXLabelBMFontCreator.cpp \
              	   ../../androidClasses/CurvedAttackState.cpp \
              	   ../../androidClasses/GarbageResourceCollection.cpp \
              	   ../../androidClasses/Jammer.cpp \
              	   ../../androidClasses/JammerDefend.cpp \
              	   ../../androidClasses/ThirdServerScene.cpp \
              	   ../../androidClasses/ThirdLoginCallBackMessage.cpp \
              	   ../../androidClasses/_internal/Source/internalJSONNode.cpp \
              	   ../../androidClasses/_internal/Source/JSONAllocator.cpp \
              	   ../../androidClasses/_internal/Source/JSONChildren.cpp \
              	   ../../androidClasses/_internal/Source/JSONDebug.cpp \
              	   ../../androidClasses/_internal/Source/JSONIterators.cpp \
              	   ../../androidClasses/_internal/Source/JSONMemory.cpp \
              	   ../../androidClasses/_internal/Source/JSONNode_Mutex.cpp \
              	   ../../androidClasses/_internal/Source/JSONNode.cpp \
              	   ../../androidClasses/_internal/Source/JSONPreparse.cpp \
              	   ../../androidClasses/_internal/Source/JSONStream.cpp \
              	   ../../androidClasses/_internal/Source/JSONValidator.cpp \
              	   ../../androidClasses/_internal/Source/JSONWorker.cpp \
              	   ../../androidClasses/_internal/Source/JSONWriter.cpp \
              	   ../../androidClasses/_internal/Source/libjson.cpp \
                   ../../androidClasses/DataCompressionUtil.cpp \
                   ../../androidClasses/CryptologyUtil.cpp \

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../androidClasses

LOCAL_WHOLE_STATIC_LIBRARIES += cocos2dx_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocosdenshion_static
LOCAL_WHOLE_STATIC_LIBRARIES += box2d_static
LOCAL_WHOLE_STATIC_LIBRARIES += chipmunk_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_extension_static

include $(BUILD_SHARED_LIBRARY)

$(call import-module,cocos2dx)
$(call import-module,cocos2dx/platform/third_party/android/prebuilt/libcurl)
$(call import-module,CocosDenshion/android)
$(call import-module,extensions)
$(call import-module,external/Box2D)
$(call import-module,external/chipmunk)
